;;; reminders.el --- Apple Reminders integration -*- lexical-binding: t -*-

;; Reads incomplete reminders from the "Emacs Inbox" list in Apple Reminders
;; and appends their notes field verbatim to the Claude inbox org file.
;;
;; The notes field is expected to contain org-mode text generated by the
;; Claude mobile app. No transformation is applied.
;;
;; Requires reminders-cli: brew install keith/formulae/reminders-cli
;;
;; Note: list name and inbox path are hardcoded here.
;; When a second inbox is needed, move these to global variables.
;;
;; Example keybinding (add to Emacs.org):
;; (global-set-key (kbd "C-c r") #'my/process-reminders)

(defun my/process-reminders ()
  "Fetch incomplete reminders from the \"Emacs Inbox\" Reminders list.
Append each reminder's notes field verbatim to the Claude inbox org file,
preceded by an import timestamp header. Mark each reminder as complete."
  (interactive)
  (let* ((inbox-file (expand-file-name "~/Documents/Notes/Inboxes/Claude Inbox.org"))
         (raw (shell-command-to-string "reminders show --format json \"Emacs Inbox\""))
         (reminders (condition-case err
                        (json-parse-string raw :array-type 'list :object-type 'alist)
                      (error
                       (message "my/process-reminders: failed to parse reminders-cli output: %s" err)
                       nil)))
         (count (length reminders)))
    (if (zerop count)
        (message "my/process-reminders: no reminders to process.")
      (with-temp-buffer
        (insert (format "\n# Imported %s\n" (format-time-string "%Y-%m-%d %H:%M")))
        (dolist (reminder reminders)
          (let ((notes (alist-get 'notes reminder))
                (id    (alist-get 'externalId reminder)))
            (when (and notes (not (string-empty-p notes)))
              (insert (replace-regexp-in-string
                       ":END:"
                       (format ":REMINDER_ID: %s\n:END:" id)
                       notes t t))
              (unless (string-suffix-p "\n" notes)
                (insert "\n")))))
        (append-to-file (point-min) (point-max) inbox-file))
      ;; Complete each reminder by externalId to avoid index-shifting issues.
      (dolist (reminder reminders)
        (shell-command (format "reminders complete \"Emacs Inbox\" %s"
                               (alist-get 'externalId reminder))))
      (let ((buf (get-file-buffer inbox-file)))
        (when buf
          (with-current-buffer buf
            (revert-buffer t t t))))
      (find-file inbox-file)
      (goto-char (point-max))
      (message "my/process-reminders: processed %d reminder(s)." count))))


(provide 'reminders)
